### ISSUE TITLE
[BUG] Error while installing with Python 3.13 on Windows

### ISSUE THREAD

**Issue by EDM115** [pysathq/pysat#180]
When i try to install it doesn't work :  
```pwsh
pip3.13 install python-sat
Collecting python-sat
  Using cached python-sat-1.8.dev13.tar.gz (5.7 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in d:\edm115\programmes\python313\lib\site-packages (from python-sat) (1.16.0)
Building wheels for collected packages: python-sat
  Building wheel for python-sat (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [475 lines of output]
      preparing cadical103
      not downloading solvers/cadical103.tar.gz since it exists locally
      extracting solvers/cadical103.tar.gz
      adapting cadical103's files
      patching cadical103
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing cadical153
      not downloading solvers/cadical153.tar.gz since it exists locally
      extracting solvers/cadical153.tar.gz
      adapting cadical153's files
      patching cadical153
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing cadical195
      not downloading solvers/cadical195.tar.gz since it exists locally
      extracting solvers/cadical195.tar.gz
      adapting cadical195's files
      patching cadical195
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing gluecard30
      not downloading solvers/glucose30.tar.gz since it exists locally
      extracting solvers/glucose30.tar.gz
      adapting gluecard30's files
      patching gluecard30
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing gluecard41
      not downloading solvers/glucose41.tar.gz since it exists locally
      extracting solvers/glucose41.tar.gz
      adapting gluecard41's files
      patching gluecard41
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing glucose30
      not downloading solvers/glucose30.tar.gz since it exists locally
      extracting solvers/glucose30.tar.gz
      adapting glucose30's files
      patching glucose30
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing glucose41
      not downloading solvers/glucose41.tar.gz since it exists locally
      extracting solvers/glucose41.tar.gz
      adapting glucose41's files
      patching glucose41
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing glucose421
      not downloading solvers/glucose421.tar.gz since it exists locally
      extracting solvers/glucose421.tar.gz
      adapting glucose421's files
      patching glucose421
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing lingeling
      not downloading solvers/lingeling.tar.gz since it exists locally
      extracting solvers/lingeling.tar.gz
      adapting lingeling's files
      extracting solvers\lingeling\druplig-009.zip
      extracting solvers\lingeling\lingeling-bbc-9230380-160707.tar.gz
      patching lingeling
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing maplechrono
      not downloading solvers/maplechrono.zip since it exists locally
      extracting solvers/maplechrono.zip
      adapting maplechrono's files
      patching maplechrono
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing maplecm
      not downloading solvers/maplecm.zip since it exists locally
      extracting solvers/maplecm.zip
      adapting maplecm's files
      patching maplecm
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing maplesat
      not downloading solvers/maplesat.zip since it exists locally
      extracting solvers/maplesat.zip
      adapting maplesat's files
      patching maplesat
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing mergesat3
      not downloading solvers/mergesat3.tar.gz since it exists locally
      extracting solvers/mergesat3.tar.gz
      adapting mergesat3's files
      patching mergesat3
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing minicard
      not downloading solvers/minicard.tar.gz since it exists locally
      extracting solvers/minicard.tar.gz
      adapting minicard's files
      patching minicard
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing minisat22
      not downloading solvers/minisat22.tar.gz since it exists locally
      extracting solvers/minisat22.tar.gz
      adapting minisat22's files
      patching minisat22
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      preparing minisatgh
      not downloading solvers/minisatgh.zip since it exists locally
      extracting solvers/minisatgh.zip
      adapting minisatgh's files
      patching minisatgh
      Le sous-syst\xe8me Windows pour Linux n'a pas de distribution install\xe9e.



      Utilisez 'wsl.exe --list --online' pour lister les distributions disponibles.

      et 'wsl.exe --install <Distro>' pour l'installer.



      Les distributions peuvent \xe9galement \xeatre install\xe9es en visitant le Microsoft Store :

      https://aka.ms/wslstore

      Code d erreur\xa0: Wsl/Service/CreateInstance/GetDefaultDistro/WSL_E_DEFAULT_DISTRO_NOT_FOUND

      running bdist_wheel
      running build
      running build_py
      creating build\lib.win-amd64-cpython-313\pysat
      copying pysat\card.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\engines.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\formula.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\pb.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\process.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\solvers.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\_fileio.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\_utils.py -> build\lib.win-amd64-cpython-313\pysat
      copying pysat\__init__.py -> build\lib.win-amd64-cpython-313\pysat
      creating build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\fm.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\genhard.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\hitman.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\lbx.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\lsu.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\mcsls.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\models.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\musx.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\optux.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\rc2.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\usage.py -> build\lib.win-amd64-cpython-313\pysat\examples
      copying examples\__init__.py -> build\lib.win-amd64-cpython-313\pysat\examples
      creating build\lib.win-amd64-cpython-313\pysat\allies
      copying allies\approxmc.py -> build\lib.win-amd64-cpython-313\pysat\allies
      copying allies\unigen.py -> build\lib.win-amd64-cpython-313\pysat\allies
      copying allies\__init__.py -> build\lib.win-amd64-cpython-313\pysat\allies
      running build_ext
      building 'pycard' extension
      creating build\temp.win-amd64-cpython-313\Release\cardenc
      "D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Icardenc -ID:\EDM115\Programmes\Python313\include -ID:\EDM115\Programmes\Python313\Include "-ID:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-ID:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpcardenc/pycard.cc /Fobuild\temp.win-amd64-cpython-313\Release\cardenc/pycard.obj -DNBUILD -DNLGLYALSAT /DINCREMENTAL -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLFILES -DNLGLDEMA -I./win
      pycard.cc
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\bitwise.hh(22): warning C4244: 'initialisation' : conversion de 'double' en 'size_t', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\bitwise.hh(40): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(134): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(148): warning C4244: 'initialisation' : conversion de 'double' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(153): warning C4244: 'initialisation' : conversion de 'double' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(296): warning C4267: 'initialisation' : conversion de 'size_t' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(310): warning C4244: 'initialisation' : conversion de 'double' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\sortcard.hh(311): warning C4244: 'initialisation' : conversion de 'double' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\card.hh(97): warning C4267: '=' : conversion de 'size_t' en 'int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\itot.hh(60): warning C4267: 'initialisation' : conversion de 'size_t' en 'unsigned int', perte possible de données
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\itot.hh(110): warning C4267: 'initialisation' : conversion de 'size_t' en 'unsigned int', perte possible de données
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\utility(269): warning C4244: 'initialisation' : conversion de 'const _Ty2' en '_Ty2', perte possible de données
              with
              [
                  _Ty2=unsigned __int64
              ]
              and
              [
                  _Ty2=int
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\utility(269): note: le contexte d’instanciation du modèle (le plus ancien) est
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\seqcounter.hh(105): note: voir la référence à l'instanciation de la fonction modèle 'int mk_yvar<Pair2IntMap,std::pair<int,unsigned __int64>>(int &,PH &,PT)' en cours de compilation
              with
              [
                  PH=Pair2IntMap,
                  PT=std::pair<int,unsigned __int64>
              ]
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\utils.hh(28): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<int,int>::pair<int,unsigned __int64,0>(const std::pair<int,unsigned __int64> &) noexcept' en cours de compilation
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\utility(276): warning C4267: 'initialisation' : conversion de 'size_t' en '_Ty2', perte possible de données
              with
              [
                  _Ty2=int
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\utility(276): note: le contexte d’instanciation du modèle (le plus ancien) est
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\cardenc\utils.hh(33): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::unordered_map<IntPair,int,IntPairHash,IntPairEqual,std::allocator<_Ty>>::insert<std::pair<std::pair<int,unsigned __int64>,int>,0>(_Valty &&)' en cours de compilation
              with
              [
                  _Ty=std::pair<const IntPair,int>,
                  _Valty=std::pair<std::pair<int,unsigned __int64>,int>
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\unordered_map(271): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<std::_List_iterator<std::_List_val<std::_List_simple_types<_Ty>>>,bool> std::_Hash<std::_Umap_traits<_Kty,int,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::emplace<std::pair<std::pair<int,unsigned __int64>,int>>(std::pair<std::pair<int,unsigned __int64>,int> &&)' en cours de compilation
              with
              [
                  _Ty=std::pair<const IntPair,int>,
                  _Kty=IntPair,
                  _Hasher=IntPairHash,
                  _Keyeq=IntPairEqual,
                  _Alloc=std::allocator<std::pair<const IntPair,int>>
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\xhash(619): note: voir la référence à l'instanciation de la fonction modèle 'std::_List_node_emplace_op2<std::allocator<std::_List_node<_Ty,std::_Default_allocator_traits<_Alloc>::void_pointer>>>::_List_node_emplace_op2<std::pair<std::pair<int,unsigned __int64>,int>>(_Alnode &,std::pair<std::pair<int,unsigned __int64>,int> &&)' en cours de compilation
              with
              [
                  _Ty=std::pair<const IntPair,int>,
                  _Alloc=std::allocator<std::pair<const IntPair,int>>,
                  _Alnode=std::allocator<std::_List_node<std::pair<const IntPair,int>,std::_Default_allocator_traits<std::allocator<std::pair<const IntPair,int>>>::void_pointer>>
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\list(585): note: voir la référence à l'instanciation de la fonction modèle 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,std::pair<std::pair<int,unsigned __int64>,int>>(_Alloc &,_Objty *const ,std::pair<std::pair<int,unsigned __int64>,int> &&)' en cours de compilation
              with
              [
                  _Alloc=std::allocator<std::_List_node<std::pair<const IntPair,int>,std::_Default_allocator_traits<std::allocator<std::pair<const IntPair,int>>>::void_pointer>>,
                  _Ty=std::pair<const IntPair,int>,
                  _Objty=std::pair<const IntPair,int>
              ]
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\xmemory(700): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<const IntPair,int>::pair<std::pair<int,unsigned __int64>,int,0>(std::pair<std::pair<int,unsigned __int64>,int> &&) noexcept' en cours de compilation
      D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\utility(276): note: voir la référence à l'instanciation de la fonction modèle 'std::pair<int,int>::pair<int,unsigned __int64,0>(std::pair<int,unsigned __int64> &&) noexcept' en cours de compilation
      "D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\EDM115\Programmes\Python313\libs /LIBPATH:D:\EDM115\Programmes\Python313 /LIBPATH:D:\EDM115\Programmes\Python313\PCbuild\amd64 "/LIBPATH:D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" /EXPORT:PyInit_pycard build\temp.win-amd64-cpython-313\Release\cardenc/pycard.obj /OUT:build\lib.win-amd64-cpython-313\pycard.cp313-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-313\Release\cardenc\pycard.cp313-win_amd64.lib
         Création de la bibliothèque build\temp.win-amd64-cpython-313\Release\cardenc\pycard.cp313-win_amd64.lib et de l'objet build\temp.win-amd64-cpython-313\Release\cardenc\pycard.cp313-win_amd64.exp
      Génération de code en cours
      Fin de la génération du code
      building 'pysolvers' extension
      creating build\temp.win-amd64-cpython-313\Release\solvers\cadical103
      creating build\temp.win-amd64-cpython-313\Release\solvers\cadical153
      creating build\temp.win-amd64-cpython-313\Release\solvers\cadical195
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose30\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose30\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose41\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose41\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose421\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\glucose421\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\gluecard30\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\gluecard30\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\gluecard41\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\gluecard41\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\lingeling
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplechrono\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplechrono\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplecm\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplecm\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplesat\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\maplesat\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\mergesat3\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\mergesat3\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\minicard\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\minicard\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\minisat22\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\minisat22\utils
      creating build\temp.win-amd64-cpython-313\Release\solvers\minisatgh\core
      creating build\temp.win-amd64-cpython-313\Release\solvers\minisatgh\utils
      "D:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Isolvers -ID:\EDM115\Programmes\Python313\include -ID:\EDM115\Programmes\Python313\Include "-ID:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include" "-ID:\EDM115\Programmes\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsolvers/cadical103/analyze.cpp /Fobuild\temp.win-amd64-cpython-313\Release\solvers/cadical103/analyze.obj -DNBUILD -DNLGLYALSAT /DINCREMENTAL -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLFILES -DNLGLDEMA -I./win -DWITH_CADICAL103 -DWITH_CADICAL153 -DWITH_CADICAL195 -DWITH_GLUECARD30 -DWITH_GLUECARD41 -DWITH_GLUCOSE30 -DWITH_GLUCOSE41 -DWITH_GLUCOSE421 -DWITH_LINGELING -DWITH_MAPLECHRONO -DWITH_MAPLECM -DWITH_MAPLESAT -DWITH_MERGESAT3 -DWITH_MINICARD -DWITH_MINISAT22 -DWITH_MINISATGH
      analyze.cpp
      C:\Users\EDM115\AppData\Local\Temp\pip-install-6jkg3445\python-sat_d7dbf5b9c99e4109964f00332049638a\solvers\cadical103\internal.hpp(21): fatal error C1083: Impossible d'ouvrir le fichier include : 'unistd.h' : No such file or directory
      error: command 'D:\\EDM115\\Programmes\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for python-sat
  Running setup.py clean for python-sat
Failed to build python-sat
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (python-sat)
```

note that it works fine with python 3.12

**Comment by alexeyignatiev** [comment]
I haven't tried it with Python 3.13 but I guess it installs for you with 3.12 because there is a precompiled binary wheel for that platform.

**Comment by EDM115** [comment]
it's especially the fact that installing pysat without an available wheel on Windows requires WSL and an installed distro for some reason  
I believe that they are Windows equivalents of tools used to build it on Linux, and that if they're not already installed they can be downloaded at build time if necessary

**Comment by alexeyignatiev** [comment]
Well, compiling it on Windows is not a trivial exercise and the current successful way of doing it was proposed by @rjungbeck. I could prebuild a wheel for Python 3.13 if there was `pypblib` compiled for that version of Python. @rjungbeck, any help with the latter please?

**Comment by alexeyignatiev** [comment]
Starting from version `1.8.dev15`, we'll have a build for Python 3.13 on Windows. I will upload the new version shortly.
